spring:
  servlet:
    # limit upload file size, if the limit is exceeded, MaxUploadSizeExceededException will be thrown
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  h2:
    console:
      enabled: true
      path: /h2-database

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 9527
    schema: classpath:db/schema-h2.sql
